### ISSUE TITLE
log.warning is not capturable by pytest

### ISSUE THREAD

**Issue by havok2063** [sdss/sdsstools#19]
The standard warnings creates a `UserWarning` when called.  This doesn't look like it's the case for `log.warnings`
```
import warnings
warnings.warn('this is a warning')                                                                                                                 
[WARNING]: this is a warning (UserWarning)

from sdsstools import get_logger                                                                                                                   
log = get_logger('test')
log.warning('this is a warning')                                                                                                                   
[WARNING]: this is a warning
```
This makes warnings issued with `log` not capturable by pytest, https://docs.pytest.org/en/stable/warnings.html#warns.  I tried recording warnings via https://docs.pytest.org/en/stable/warnings.html#recwarn but that didn't work either.  

My temporary workaround is to replace all my `log.warning` with `warnings.warn` but it would be great to consolidate it so we could use the `log` everywhere rather than `log`+`warnings`.  I imagine if no warning type is specified, the logger could default to `UserWarning`.

Also, specifying a `UserWarning` in `log.warning` results in the following error:
```
log.warning('this is a warning', UserWarning)                                                                                                      
--- Logging error ---
Traceback (most recent call last):
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/sdsstools/logger.py", line 71, in format
    warning_category_groups = WARNING_RE.match(record_cp.args[0])
TypeError: expected string or bytes-like object
Call stack:
  File "/Users/Brian/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 558, in mainloop
    self.interact()
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 549, in interact
    self.run_cell(code, store_history=True)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-098ccee82957>", line 1, in <module>
    log.warning('this is a warning', UserWarning)
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1395, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/Users/Brian/anaconda3/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/Users/Brian/anaconda3/lib/python3.7/site-packages/sdsstools/logger.py", line 248, in handle
    return super().handle(record)
Message: 'this is a warning'
Arguments: (<class 'UserWarning'>,)
```

**Comment by albireox** [comment]
I think that's not a bug. `log.warning` is different from `warnings.warn` (albeit arguably confusing). `log.warning` is just a log message with level `WARNING`. `warnings.warn` is a system warning that can be filtered, ignored, subclassed, etc.

What the code does is to log all `warnings.warn` as a `WARNING` record, but the opposite is not true: a `log.warning` does not issue a `warnings.warn`. If you want to use specific subclasses of `UserWarning` then you would need to use `warnings.warn`.

**Comment by havok2063** [comment]
Yeah that makes sense.  I was mainly hoping there was a workaround as a matter of convenience, but I can deal with using both warnings and log.
